#must plugin
[[plugins]]
#dein.vim
repo = 'Shougo/dein.vim'

[[plugins]]
#カラーテーマ
repo = 'ulwlu/elly.vim'
hook_add = '''
colorscheme elly
set termguicolors
'''

[[plugins]]
#自動で括弧()を閉じる
repo = 'Townk/vim-autoclose'

[[plugins]]
#ステータスラインのカスタマイズ
repo = 'itchyny/lightline.vim'

[[plugins]]
#インデントラインの可視化
repo = 'Yggdroot/indentLine'

[[plugins]]
#末尾の無駄なスペースをハイライト/削除する
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
#ヤンクされた範囲がハイライトする
repo = 'machakann/vim-highlightedyank'
hook_add = '''
let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
#コメントアウト
repo = 'tpope/vim-commentary'

[[plugins]]
#テキストオブジェクトで指定した範囲を任意の文字で囲う
repo = 'machakann/vim-sandwich'


[[plugins]]
#:helpで表示される英語のヘルプを日本語化する
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
#ウィンドウのリサイズをかんたんにする
repo = 'simeji/winresizer'

[[plugins]]
#マルチカーソルを可能にする
repo = 'mg979/vim-visual-multi'
hook_add = '''

'''

[[plugins]]
#セッションを保存・復元する
repo = 'xolox/vim-session'
hook_add = '''
let g:session_autosave = 'yes'
let g:session_autoload = 'yes'
'''

[[plugins]]
#vim-sessionが依存するためインストール
repo = 'xolox/vim-misc'

[[plugins]]
#.editorconfigがある場合、neovimの設定に上書きする
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
#自動保存
repo = 'vim-scripts/vim-auto-save'
hook_add ='''
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#default_hidden=1
'''

[[plugins]]
repo ='yuki-yano/fern-preview.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
augroup my-glyph-palette
autocmd! *
autocmd FileType fern call glyph_palette#apply()
autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END
'''

#try plugin

#[[plugins]]
#vimをVSCodeのようなIDEライクな開発環境にする
#repo = 'neoclide/coc.nvim'
#source = 'release'
#build = 'coc#util#install()'


